from enum import Enum


class InformationFieldType(Enum):
    TEXT_INFORMATION_FIELD = 'TEXT_INFORMATION_FIELD'
    MAP_INFORMATION_FIELD = 'MAP_INFORMATION_FIELD'
    FILE_INFORMATION_FIELD = 'FILE_INFORMATION_FIELD'
